# Generated by Django 5.0.6 on 2024-06-25 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestclasses',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='classes',
            name='request_classes_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.requestclasses'),
        ),
    ]
