# Generated by Django 5.0.6 on 2024-06-26 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classes_id_alter_requestclasses_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='request_classes_id',
        ),
        migrations.AddField(
            model_name='requestclasses',
            name='classes_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
            preserve_default=False,
        ),
    ]
