# Generated by Django 5.0.6 on 2024-06-26 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('user', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='user_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
