# Generated by Django 5.0.1 on 2024-06-25 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeachersModel',
            new_name='Teachers',
        ),
    ]
