# Generated by Django 5.0.1 on 2024-06-27 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teachers_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('subject', models.CharField(choices=[('BIO', 'Biology'), ('MATH', 'Mathematics'), ('CHEM', 'Chemistry'), ('PHYSC', 'Physics'), ('ENG', 'English')], max_length=8)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'curriculum',
            },
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('degree_title', models.TextField()),
                ('degree_url', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('curriculum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.curriculum')),
            ],
            options={
                'db_table': 'academics',
            },
        ),
    ]
