# Generated by Django 5.0.6 on 2024-06-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=420)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=120)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['created_at'],
                'unique_together': {('email', 'username')},
            },
        ),
    ]
